### ISSUE TITLE
Enter password while deleting does not work.

### ISSUE THREAD

**Issue by jjjasper** [bponomarenko/autoconfig-app#1]
When no credentials are stored, and delete button is clicked, a dialog appears to enter credentials.
After entering username and password only the back button can be clicked. The other button (delete, next, continue.... I can't remember) is not enabled.

**Comment by bponomarenko** [comment]
@jjjasper It should be fixed in the recent released v0.4.0. Can you please check it there?

**Comment by bponomarenko** [comment]
Fixed
