### ISSUE TITLE
Mandatory parameter was added for stack "dbs-microservices".

### ISSUE THREAD

**Issue by jjjasper** [bponomarenko/autoconfig-app#8]
A mandatory parameter called "capabilities" was added to the request to create a dbs-microservices environment. The value is a comma separated list of capability names. (eg 

> ContactManager,ProductSummary,Transactions,MessageCenter,Notifications,Actions

) More capabilities will be added.

**Comment by bponomarenko** [comment]
@jjjasper Is it mandatory? I was able to create this environment without specifying this query parameter.

**Comment by jjjasper** [comment]
Using curl it shows this result:

curl -X POST -k -u someone@somewhere.com:************ [AUTOCONFIGURL]/dbs-microservices
{"message": "'capabilities' param must be specified for dbs-microservices stack"}

**Comment by bponomarenko** [comment]
@jjjasper Looks like validation for _capabilities_ param only works when no other params are specified. But got it, thanks.

**Comment by bponomarenko** [comment]
Implemented in v.1.3.0
